brew 'awscli'
brew 'mackup'
brew 'mas'
brew 'nvm'
brew 'postgresql'
brew 'pyenv'
brew 'rbenv'
brew 'ruby-build'
brew 'yarn'
brew 'zsh-git-prompt'

cask '1password'
cask 'authy'
cask 'bartender'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'iterm2'
cask 'kap'
cask 'moom'
cask 'menumeters'
cask 'monitorcontrol'
cask 'rectangle'
cask 'rocket'
cask 'slack'
cask 'spotify'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'zoom'

tap 'homebrew/cask-drivers'
cask 'logitech-options'

mas 'Bear', id: 1091189122
mas 'Hand Mirror', id: 1502839586
