tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "gnupg"
brew "sqlite"
brew "mackup"
brew "mas"
brew "node"
brew "syncthing"
brew "yarn"
brew "zsh-git-prompt"
cask "1password"
cask "around"
cask "authy"
cask "bartender"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "freeze"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "logitech-options"
cask "loom"
cask "menumeters"
cask "monitorcontrol"
cask "obsidian"
cask "rectangle"
cask "slack"
cask "sonos"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"
mas "Bear", id: 1091189122
mas "Drafts", id: 1435957248
mas "GIPHY CAPTURE", id: 668208984
mas "Hand Mirror", id: 1502839586
